# -*- coding: utf-8 -*-
"""Product Review Summarizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15p19t_pCFCxgZisA0b3rDs1WYk23pE0k
"""

import numpy as np
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64
!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

# Load Sentiment analysis model
sentiment = pipeline("sentiment-analysis")

# Sample product review (you can change only this text later)
reviews = "The laptop starts quickly and works smoothly for daily tasks. The screen quality is clear and good for watching video. Battery backup is average and needs charging often. The fan makes noise when many apps are running. Overall, it is a good laptop for students but not the gaming"

# Split review into sentences:
sentences = reviews.split(".")
pros = []
cons = []

for s in sentences:
    s = s.strip()
    if s == "":
        continue
    result = sentiment(s)[0]

    if result["label"] == "POSITIVE":
        pros.append(s)
    elif result["label"] == "NEGATIVE":
        cons.append(s)

# Take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]

# Create table
df = pd.DataFrame({
    "pros": pros,
    "cons": cons
})

print(df)