# -*- coding: utf-8 -*-
"""Sentence similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOEYHkCtESdfL7buRn0Vr_PDTo-RAhfe
"""

!pip install sentence_transformers
from sentence_transformers import SentenceTransformer, util

# Load the Model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Take input from user
text1 = input("Enter Text: ")
text2 = input("Enter Text: ")

# convert text to Embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

# Calculate Similarity
similarity = util.cos_sim(embedding1, embedding2)

# show result
print("\n Similarity Score :", round(float(similarity), 2))

if similarity > 0.75:
    print("similarity level: High")
    elif similarity > 0.4:
        print("similarity level: Medium")
        else:
            print("similarity level: Low")