# -*- coding: utf-8 -*-
"""Text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fmGGGzTj7Glu-vxDxMcFxxmWK0r_dMM
"""

!pip install transformers torch
from transformers import pipeline

# load text generation model (Gen AI)
generator = pipeline(
    "text-generation",
        model = "gpt2"
        )

# Input Prompt
prompt = "Artificial Intelligence in finance will"

# Generate text
result = generator(prompt, max_length = 50, num_return_sequences = 1)

print("AI Generated Text:")
print(result[0]['generated_text'])